TOOLBASE = Kinship  KinshipX  MathCholesky  MathDeriv  MathFloatVector  MathGenMin  MathGold  MathNormal MathSVD  TraitTransformations

HDRONLY = Rmath.h 

USER_LIBS =  ../libRmath.a

PARENT_MAKE = Makefile.extlib
include ../Makefile.inc
