TOOLBASE = PDFchartaxis    PDFchartline    PDFfont       PDFinfo PDFchartbar     PDFchartmarker  PDFgridcell   PDFlinechart PDFchartbasics  PDFchartobject  PDFgrid       PDFpage PDFchartlegend  PDF             PDFhistogram  PDFpageobject PDFlinechartwithpolygon PDFmanhattan
HDRONLY =

USER_LIBS =  ../libRmath.a

CFLAGS ?= $(OPTFLAG) -pipe -Wno-write-strings 


PARENT_MAKE = Makefile.extlib
include ../Makefile.inc

