#!/bin/bash

yourpath="/net/wonderland/home/saichen/Raremetal/bin"

../bin/raremetalworker --ped example1.ped --dat example1.dat --vcf example1.vcf.gz --traitName QT1 --inverseNormal --makeResiduals --kinSave --kinGeno --prefix STUDY1 

../bin/raremetalworker --ped example2.ped --dat example2.dat --vcf example2.vcf.gz --traitName QT1 --inverseNormal --makeResiduals --kinSave --kinGeno --prefix STUDY2

rm -f STUDY1.QT1.singlevar.score.txt.gz* STUDY2.QT1.singlevar.score.txt.gz* STUDY1.QT1.singlevar.cov.txt.gz* STUDY2.QT1.singlevar.cov.txt.gz*

bgzip STUDY1.QT1.singlevar.score.txt; tabix -c "#" -s 1 -b 2 -e 2 -f STUDY1.QT1.singlevar.score.txt.gz
bgzip STUDY2.QT1.singlevar.score.txt; tabix -c "#" -s 1 -b 2 -e 2 -f STUDY2.QT1.singlevar.score.txt.gz

bgzip STUDY1.QT1.singlevar.cov.txt; tabix -c "#" -s 1 -b 2 -e 2 -f STUDY1.QT1.singlevar.cov.txt.gz
bgzip STUDY2.QT1.singlevar.cov.txt; tabix -c "#" -s 1 -b 2 -e 2 -f STUDY2.QT1.singlevar.cov.txt.gz

../bin/raremetal --summaryFiles summaryfiles --covFiles covfiles --groupFile group.file --SKAT --burden --MB --VT --hwe 1.0e-05 --callRate 0.95 --longOutput --tabulateHits --hitsCutoff 1e-05 --prefix COMBINED.QT1 --labelHits
